name: Build VMSpoofer

on:
  workflow_dispatch: # بيسمح لك تشغل الـ Build يدوياً

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Project
      run: |
        msbuild VMSpoofer.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VMSpoofer-Executable
        path: x64/Release/*.exe
